k8s_namespace: "casopractico2-kubernetes"
directorio_trabajo: "/tmp"
aplicacion:
  definicion: "stateless-mysql.yaml"
  databases:
    nombre: mysql
    imagen: acrunir.azurecr.io/mysql:latest
    replicas: 1
    recursos:
      cpu: 500m
      memoria: 500Mi
    limites:
      cpu: 1
      memoria: 1Gi
    puerto: 3306


    
