---
- name: 'login and push images'
  hosts: webservers
  remote_user: azureuser
  become: true
  vars_files:
    - vars/00_vars.yaml
  tasks:
    - name: Login to default registry and create ${XDG_RUNTIME_DIR}/containers/auth.json
      containers.podman.podman_login:
        username: "{{ username }}"
        password: "{{ password }}"
        registry: "{{ registry }}"
        executable: '/opt/podman/bin'
    - name: Push an image WebApp using an auth file
      containers.podman.podman_image:
        name: "{{ image_name }}"
        tag:  latest
        push: yes
        #auth_file: /etc/containers/auth.json
        username: "{{ username }}"
        password: "{{ vault_registry_password }}"
        push_args:
          dest: "{{ registry }}"
    - name: Push an image MongoDB using an auth file
      containers.podman.podman_image:
        name: "{{ image_name_db }}"
        tag: latest
        push: yes
        #auth_file: /etc/containers/auth.json
        username: "{{ username }}"
        password: "{{ vault_registry_password }}"
        push_args:
          dest: "{{ registry }}"