---
- name: 'Pull and deploy WebApp image'
  hosts: webservers
  remote_user: azureuser
  become: true
  vars_files:
    - vars/00_vars.yaml
  tasks:
    - name: Pull an webapp image
      containers.podman.podman_image:
          name: "{{ image_name }}"
          tag: latest
          #auth_file: /etc/containers/auth.json
          pull: yes
          username: "{{ username }}"
          password: "{{ password }}"
    - name: Create container
      containers.podman.podman_container:
          name: web
          image: "{{ image_name }}"
          ports:
            - "8080:443"
    - name: Create systemd script for created container
      become: true
      shell: podman generate systemd --name web > /etc/systemd/system/container-web.service
    - name: Force systemd to reread configs
      become: true
      systemd: daemon_reload=yes
    - name: Enable container service
      become: true
      systemd:
        name: container-web.service
        enabled: true
        state: started


